
const HOUR_HEIGHT = 80
const UNIT_NUM_IN_SQUARE = 4

export const Constants = {
  HOUR_HEIGHT: HOUR_HEIGHT,
  MINUTE_HEIGHT: HOUR_HEIGHT / 60,
  UNIT_NUM_IN_SQUARE: UNIT_NUM_IN_SQUARE,
  UNIT_HEIGHT: HOUR_HEIGHT / UNIT_NUM_IN_SQUARE,
  UNIT_MINUTES: 60 / UNIT_NUM_IN_SQUARE
}

