
const SQUARE_HEIGHT = 80
const UNIT_NUM_IN_SQUARE = 4

export const Constants = {
  SQUARE_HEIGHT: SQUARE_HEIGHT,
  UNIT_NUM_IN_SQUARE: UNIT_NUM_IN_SQUARE,
  UNIT_HEIGHT: SQUARE_HEIGHT / UNIT_NUM_IN_SQUARE,
  UNIT_MINUTES: 60 / UNIT_NUM_IN_SQUARE
}

